#!/usr/bin/with-contenv bash
SOCAT_USER=${SOCAT_USER:-abc}
SOCAT_PRINTER_LINK=${SOCAT_PRINTER_LINK:-/dev/ttyACM0}
SOCAT_PRINTER_HOST=${SOCAT_PRINTER_HOST:-localhost}
SOCAT_PRINTER_PORT=${SOCAT_PRINTER_PORT:-23}

PARAMS="-d -d pty,link=${SOCAT_PRINTER_LINK},rawer,wait-slave,user=${SOCAT_USER},group=${SOCAT_USER},mode=777 tcp:${SOCAT_PRINTER_HOST}:${SOCAT_PRINTER_PORT}"

exec \
	s6-setuidgid root socat $PARAMS

